### ISSUE TITLE
CASAL2 using Adol-C fails to pass simple (whole system) tests where R succeeds

### ISSUE THREAD

**Issue by mkienzle** [NIWAFisheriesModelling/CASAL2#264] opened 2018-10-10 03:37 UTC
Dear all,

[Simulations of a fishery](https://github.com/mkienzle/LearningCASAL2/blob/production/TestCASAL2_withSimulatedData/StockDescriptionInNumbers/EstimateSingleConstantRecruitment/ByPassingInitialAbundancesToCASAL2/ForWindows/SimulationStudy.R) have been developed to learn how to use CASAL2 to estimate parameters. 

When CASAL2 capability to estimate a single recruitment parameter, using Adol-C, is put to the test, this study shows that CASAL2 fails at this task in [5-20% of the cases](https://github.com/mkienzle/LearningCASAL2/blob/production/TestCASAL2_withSimulatedData/StockDescriptionInNumbers/EstimateSingleConstantRecruitment/ByPassingInitialAbundancesToCASAL2/ForLinux/Results/Graphics/SimVsEst.png) while [an R version of the same stock assessment](https://github.com/mkienzle/LearningCASAL2/blob/production/TestCASAL2_withSimulatedData/StockDescriptionInNumbers/EstimateSingleConstantRecruitment/ByPassingInitialAbundancesToCASAL2/ForLinux/EstimateRecruitmentInR.R) does estimate recruitment [without making a single error](https://github.com/mkienzle/LearningCASAL2/blob/production/TestCASAL2_withSimulatedData/StockDescriptionInNumbers/EstimateSingleConstantRecruitment/ByPassingInitialAbundancesToCASAL2/ForLinux/Results/Graphics/SimVsEst2.png).

In this example, either CASAL2 config files are not setup properly or CASAL2 is not capable of using Adol-C to estimate the correct value of a single parameter used to simulate the dynamic of a simple fishery or else.

**Comment by hoyles** [comment] 2018-10-11 04:39
I'm getting an error - my version of casal2 (not the latest) can't find the report type 'year_age_matrix', and it's not in the manual. 

At line 8 in report.csl2: Block object type or sub-type is invalid.
Object Type: report
Sub-Type: year_age_matrix

@report annual_age_1st4Months
type year_age_matrix
time_step January-April

**Comment by mkienzle** [comment] 2018-10-14 20:29
The error above was identified as resulting from @hoyles and @mkienzle using different version of CASAL2.

Further work evidenced that @mkienzle work was not reproducible on a Windows machine so the simulations have be adapted to run on MS Windows.

To reproduce the errors reported in this issue on MS Windows, follow the instruction below:

1. Save and extract this [archive](https://github.com/mkienzle/LearningCASAL2/blob/production/TestCASAL2_withSimulatedData/StockDescriptionInNumbers/EstimateSingleConstantRecruitment/forWin.zip)
2. Use the sub-directory ByPassingInitialAbundancesToCASAL2/ForWindows your R working directory
3. Install SAFR in R using the following commands:  library(devtools); install_github("mkienzle/SurvivalAnalysisForFisheries/Scripts/SAFR")
4. source(“run.R”)
5. check the results in the newly created plots in PDF files stored in subdirectory Results/Graphics

cheers,
marco

**Comment by Zaita** [comment] 2018-10-15 20:33
I've tested this with ADOLC-C, BetaDiff and Numerical Differences. These all give the same objective value function as the -r of 128.743. So either the -r is optimised, or the estimate values are not sufficient enough to move the objective function resulting in proper optimisation.

I cannot see an issue specifically with ADOL-C

**Comment by Zaita** [comment] 2018-10-15 21:11
[TwoSex.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/2480571/TwoSex.zip)

Attaching. Casal2 build with working TwoSex configs for all main minimisers

**Comment by Zaita** [comment] 2018-10-15 22:05
Closing: Not reproducible.

**Comment by mkienzle** [comment] 2018-10-16 01:43
Explanation about how to resolve this issue are not clear enough, hence the issue has been re-open.

@Zaita : please, provide further explanation to "Marco Kienzle #264 Cannot reproduce. ADOL-C looks fine to me. But the model provided does not minimiser with any minimise"

**Comment by mkienzle** [comment] 2018-10-16 03:50
> I've tested this with ADOLC-C, BetaDiff and Numerical Differences. These all give the same objective value function as the -r of 128.743. So either the -r is optimised, or the estimate values are not sufficient enough to move the objective function resulting in proper optimisation.
> 
> I cannot see an issue specifically with ADOL-C

This issue reports that when CASAL2 is tested with 100 simulated data-sets, in 5 to 20% of the cases CASAL2 fails to provide the correct answer. 

It is not clear how testing a single model with 3 different minimization libraries, as presented above by @Zaita, solves this issue: please explain.

**Comment by mkienzle** [comment] 2018-10-16 03:51
> [TwoSex.zip](https://github.com/NIWAFisheriesModelling/CASAL2/files/2480571/TwoSex.zip)
> 
> Attaching. Casal2 build with working TwoSex configs for all main minimisers

@Zaita : TwoSex model is irrelevant to this issue: it is not TwoSex model that is tested in this issue.

**Comment by Zaita** [comment] 2018-10-16 06:57
Please provide a model with command line parameters where the answer is incorrect. Please provide expected values and document how Casal2 varies from these (e.g. what is particular about this use case that could cause different values when other models work as expected?)

**Comment by Craig44** [comment] 2018-10-16 07:07
@mkienzle Can you supply a zip (for windows) for the R library SAFR? it is not available on CRAN at least for R version 3.4.4. If this package does not contain the function Caaa2Coaa() can you also supply that, as I can not locate it in your repo. I will attempt to solve this issue, if you supply the necessary information to follow your R scripts. In my experience these issues arise due to a discrepancy between your operating model (R simulator) and estimation model (casal2).

**Comment by Craig44** [comment] 2018-10-16 09:05
Right so on investigation of one of the runs, I set the seed `set.seed(123)` and when `i = 2` I got a mis-fit. So you are right that betadiff could not find the minimum when optimise in R does, I did try the casal2 minimiser `de_solver` and that solved the problem, but some of the other minimsers did not `adolc.`. When I changed the starting value (to the left of the solution) allI the minimisers also found the correct solution. Although initially this is alarming, When there was a mis-fit like what @mkienzle has found it is obvious (by looking at the residuals) that we have failed to reach a satisfactory minimization. I am not sure how you want to progress from here, it is an interesting find. I have attached a figure looking at the the profile of the surface with respect to the parameter of interest.

![ll_surface](https://user-images.githubusercontent.com/13144077/47005137-a004d580-d18f-11e8-9720-8c1414f9952a.png)

**Comment by mkienzle** [comment] 2018-10-16 21:22
Scott and the work above done by Craig (thanks Scott and Craig for digging into this issue) suggests that Adol-C is poorly suited for single parameter estimation problems and DE solver should be used instead. The fact is that the routine used in R (optimize) optimizes for a single parameter. 

POSSIBLE FIX: replace Adol-C by DE solver to check if this solve the issue.

**Comment by Zaita** [comment] 2018-12-30 22:15
Closing this.

Result: Estimation of model parameters by an auto-differentiation minimiser (CppAD, ADOL-C, BetaDiff) is an estimation process. They're designed and suited for large numbers of parameters. They perform adequately on all samples models so far.

If a user is estimating a single parameter, their model is likely not suited for use with a modelling platform like Casal2/SPM. If they must use Casal2, then it is recommended that the user try a minimiser like DLIB or DE-Solver as these are more likely to resolve a single parameter.

**Closed by Zaita** 2018-12-30 22:15 UTC
Labels: useful
