### ISSUE TITLE
Build of cppad fails on linux

### ISSUE THREAD

**Issue by tetoroa** [NIWAFisheriesModelling/CASAL2#217] opened 2018-05-09 22:25 UTC
The error is due to this piece of code in the cppad/linux.py:
   if os.path.exists(ipOptFileName + '.tgz'):
      os.system('tar -xvzf ' + ipOptFileName + '.tgz 1> casal2_unzip.log 2>&1')
      os.system('tar -xvzf ' + ipOptFileName + '.tar 1> casal2_untar.log 2>&1')

Which should actually read
    if os.path.exists(ipOptFileName + '.tgz'):
      os.system('tar -xvzf ' + ipOptFileName + '.tgz 1> casal2_untar.log 2>&1')
    elif os.path.exists(ipOptFileName + '.tar'):
      os.system('tar -xvzf ' + ipOptFileName + '.tar 1> casal2_untar.log 2>&1')

**Comment by Zaita** [comment] 2018-05-22 22:19
Hello,
The elif could never be true. Because the file provided with Casal2 is a .tgz the first condition of that statement will always be true. There would never exist a ipOptFileName.tar that exists without decompressing the .tgz.

What version of Linux are you having the issue with? 
What is the issue?

**Comment by Zaita** [comment] 2018-08-07 23:07
@tetoroa Do you have an update to this? If not I'll be closing this issue.

**Comment by Zaita** [comment] 2018-08-12 20:09
No response from poster. Nobody else can reproduce this.

**Closed** 2018-08-12 20:09 UTC
